title: "CS Course"
description: "A collection of computer science tutorials and articles"
theme: "minima"
include:
  - "*.tsx"
  - "*.ipynb"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
